// The SQL dialects: every place the store's SQL text depends on the engine is a hook
// here, so runtime/store/** builds statements through `drv.dialect` and never spells
// an engine-specific keyword itself. Pure text in, text out — no I/O, no imports —
// which is also why the PostgreSQL dialect can be tested (tests/dialect.test.mjs)
// with no server. SQLite is still the only executor; `postgres` is what S6 will run.
const quote = (id) => `"${String(id).replaceAll('"', '""')}"`;
const UNITS = { day: '%Y-%m-%d', month: '%Y-%m', year: '%Y' };
const LENGTHS = { day: 10, month: 7, year: 4 };
// What the user typed is what is searched for: "50%" is a percent sign, not "anything".
const escapeLike = (v) => String(v).replace(/[\\%_]/g, (c) => `\\${c}`);
const bytes = (s) => new TextEncoder().encode(s).length;
const PG_NAME_MAX = 63; // PostgreSQL silently truncates identifiers at 63 bytes

// 32-bit FNV-1a as 8 hex digits: deterministic, no dependency, enough to tell two long names apart.
function fnv(s) {
  let h = 0x811c9dc5;
  for (const b of new TextEncoder().encode(s)) h = Math.imul(h ^ b, 0x01000193) >>> 0;
  return h.toString(16).padStart(8, '0');
}

// PostgreSQL would cut a longer name itself, so the name the store looks for on the next
// boot would never match the one the catalog holds and the index would be re-created
// every time. Cut it ourselves, on a character boundary, and end it with a hash of the
// whole name so two long names with the same head stay apart.
function pgIndexName(table, cols) {
  const full = `idx_${table}_${cols.join('_')}`;
  if (bytes(full) <= PG_NAME_MAX) return full;
  let head = '';
  for (const ch of full) { if (bytes(head + ch) > PG_NAME_MAX - 9) break; head += ch; }
  return `${head}_${fnv(full)}`;
}

// The parts both engines share are written once here; `p` holds what differs.
function build(name, p) {
  const d = { name, quote, escapeLike, ...p };
  d.phs = (n, from = 1) => Array.from({ length: n }, (_, i) => p.ph(from + i)).join(',');
  // 0/1 out of a condition: the store's booleans are integers, never the engine's boolean type.
  d.boolInt = (cond) => `(CASE WHEN ${cond} THEN 1 ELSE 0 END)`;
  d.like = (col, ph) => `LOWER(${col}) LIKE ${ph} ESCAPE '\\'`;
  d.lowerEq = (col, ph) => `LOWER(${col})=LOWER(${ph})`;
  d.likeArg = (v) => `%${escapeLike(String(v).toLowerCase())}%`;
  d.insert = (table, cols) => (cols.length
    ? `INSERT INTO ${quote(table)} (${cols.map(quote).join(',')}) VALUES (${d.phs(cols.length)})`
    : `INSERT INTO ${quote(table)} DEFAULT VALUES`) + p.returning;
  d.createTable = (table, cols, { ifNotExists = false, serial = true } = {}) => {
    const defs = cols.map(([n, t]) => `${quote(n)} ${p.colType(t)}`);
    if (serial) defs.unshift(`id ${p.idType}`);
    return `CREATE TABLE ${ifNotExists ? 'IF NOT EXISTS ' : ''}${quote(table)} (${defs.join(', ')})`;
  };
  d.addColumn = (table, col, type) => `ALTER TABLE ${quote(table)} ADD COLUMN ${quote(col)} ${p.colType(type)}`;
  d.createIndex = (idx, table, cols) => `CREATE INDEX IF NOT EXISTS ${quote(idx)} ON ${quote(table)} (${cols.map(quote).join(', ')})`;
  d.dropIndex = (idx) => `DROP INDEX IF EXISTS ${quote(idx)}`;
  return d;
}

export const sqlite = build('sqlite', {
  ph: () => '?',
  idType: 'INTEGER PRIMARY KEY AUTOINCREMENT',
  returning: '', // the driver reads the new id from the statement result (lastInsertRowid)
  colType: (t) => t,
  // strftime and not SUBSTR: a `time` field accepts anything Date parses, and strftime
  // (unlike SUBSTR) normalises or refuses such text; changing that would change answers.
  bucket: (col, unit) => `strftime('${UNITS[unit]}', ${col})`,
  // SQLite sorts NULLs first ascending and last descending on its own, and its ties come
  // out in scan order; nothing to add.
  order: (col, dir) => `${col} ${dir}`,
  collate: (expr) => expr,
  // SQLite binds `$today` by name from one object passed as the first parameter.
  named: (n) => n,
  args: (_names, named, vals) => [named, ...vals],
  upsert: (table, cols) => `INSERT OR REPLACE INTO ${quote(table)} (${cols.map(quote).join(', ')}) VALUES (${sqlite.phs(cols.length)})`,
  tablesSql: () => ({ sql: `SELECT name FROM sqlite_master WHERE type='table'`, params: [] }),
  columnsSql: (table) => ({ sql: `PRAGMA table_info(${quote(table)})`, params: [] }),
  indexesSql: (table, prefix = '') => ({
    sql: `SELECT name FROM sqlite_master WHERE type='index' AND tbl_name=? AND name LIKE ? ESCAPE '\\'`,
    params: [table, `${escapeLike(prefix)}%`],
  }),
  indexName: (table, cols) => `idx_${table}_${cols.join('_')}`,
});

export const postgres = build('postgres', {
  ph: (n) => `$${n}`,
  idType: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  returning: ' RETURNING id',
  // int, bool and money are all INTEGER in the field registry; money in minor units
  // overflows int4 at about 21M major units, so every one of them is a BIGINT here.
  colType: (t) => t.replace(/\bINTEGER\b/g, 'BIGINT'),
  bucket: (col, unit) => `SUBSTR(${col}, 1, ${LENGTHS[unit]})`,
  // Reproduce SQLite's order: NULLs smallest (first ascending, last descending), text in
  // byte order (COLLATE "C"), and ties by id — the tie-break lives here only, because
  // SQLite's own order among equals is unspecified and must not change under it.
  // An output alias cannot take a COLLATE in ORDER BY, so a grouped text column is collated where it is selected.
  collate: (expr) => `${expr} COLLATE "C"`,
  order: (col, dir, { text = false, tie = false } = {}) =>
    `${col}${text ? ' COLLATE "C"' : ''} ${dir} NULLS ${dir === 'ASC' ? 'FIRST' : 'LAST'}${tie ? ', id ASC' : ''}`,
  // No named parameters: `today`/`now` become the first numbered ones, in the order the plan lists them.
  named: (_n, i) => `$${i + 1}`,
  args: (names, named, vals) => [...names.map((n) => named[n]), ...vals],
  upsert: (table, cols, key = 'id') => `INSERT INTO ${quote(table)} (${cols.map(quote).join(', ')}) VALUES (${postgres.phs(cols.length)})`
    + ` ON CONFLICT (${quote(key)}) DO UPDATE SET ${cols.filter((c) => c !== key).map((c) => `${quote(c)}=EXCLUDED.${quote(c)}`).join(', ')}`,
  tablesSql: () => ({
    sql: `SELECT table_name AS name FROM information_schema.tables WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'`,
    params: [],
  }),
  columnsSql: (table) => ({
    sql: `SELECT column_name AS name, data_type AS type FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = $1 ORDER BY ordinal_position`,
    params: [table],
  }),
  indexesSql: (table, prefix = '') => ({
    sql: `SELECT indexname AS name FROM pg_indexes WHERE schemaname = current_schema() AND tablename = $1 AND indexname LIKE $2 ESCAPE '\\'`,
    params: [table, `${escapeLike(prefix)}%`],
  }),
  indexName: pgIndexName,
});
