#!/usr/bin/env node
// The mutation gate. Coverage says the line ran; this says the tests would have
// noticed if the line were wrong. A mutation that survives is a hole in the suite.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';

const MUTATIONS = [
  // The four defects the apps actually found — the suite must catch each of them again.
  { name: 'bool coercion forgets numeric 1 (defect found by todo)', file: 'runtime/fields.mjs',
    find: "raw === true || raw === 1 ||", replace: "raw === true ||" },
  { name: "a new column is not backfilled with its default (defect found by todo)", file: "runtime/store.mjs",
    find: "const n = this.drv.run(\n            `UPDATE ${q(table)} SET ${q(f.name)}=${ph(1)} WHERE ${q(f.name)} IS NULL`, [seed]).changes;",
    replace: "const n = 0;" },
  { name: 'an unchecked box on create falls back to the declared default (defect found by drivers)',
    file: 'runtime/interp.mjs',
    find: "      if (f.kind !== 'bool' || submitted[f.name] !== undefined) continue;\n      if (shown && !shown.includes(f.name)) continue;\n      submitted[f.name] = 'false';",
    replace: "      if (true) continue;" },
  { name: 'a boolean ignores its declared labels (regression found by todo)', file: 'runtime/fields.mjs',
    find: "    format: (v, f, { esc, labels }) => { const pair = labels?.[f.name] || ['No', 'Yes'];", replace: "    format: (v, f, { esc }) => { const pair = ['No', 'Yes'];" },

  // Storage
  { name: "list ignores the declared filters", file: "runtime/store/query.mjs",
    find: "    clauses.push(`${q(field)}=${ph(vals.length + 1)}`);\n    vals.push(coerce(f, cmp));",
    replace: "    void field; void cmp;" },
  { name: "search matches everything", file: "runtime/store/query.mjs",
    find: "    cls.push('(' + search.map((f) => { vals.push(likeArg(q)); return like(quote(f), ph(vals.length)); }).join(' OR ') + ')');",
    replace: "    cls.push('(1=1)');" },
  { name: 'sort direction is inverted', file: 'runtime/store/query.mjs',
    find: "sort.dir === 'asc' ? 'ASC' : 'DESC'", replace: "sort.dir === 'asc' ? 'DESC' : 'ASC'" },
  { name: 'aggregate ignores the grouping', file: 'runtime/store/query.mjs',
    find: "  if (groupBy) sql += ' GROUP BY grp';", replace: "  if (false) sql += '';" },
  { name: 'insert ignores declared defaults', file: 'runtime/store.mjs',
    find: "      const use = given === undefined || given === '' ? defaultValue(f) : Store.prepareValue(f, this.checkValue(entity, f, given));",
    replace: "      const use = given === undefined || given === '' ? null : Store.prepareValue(f, this.checkValue(entity, f, given));" },
  { name: 'a removed field is dropped silently', file: 'runtime/store.mjs',
    find: "      if (orphan.length && !this.graph.allowDestructive) {", replace: "      if (false) {" },

  // The checker
  { name: 'unknown blocks are accepted', file: 'runtime/check/steps.mjs',
    find: "      if (!block) {", replace: "      if (false) {" },
    // (the following lines still run; the point is that the error is never raised)
  { name: 'unknown fields in a view are accepted', file: 'runtime/check/scope.mjs',
    find: "    if (!known(e).includes(f)) {", replace: "    if (false) {" },
  { name: 'a related section may point anywhere', file: 'runtime/check/override.mjs',
    find: "      else if (f.target !== entity) err(`${p}/via`, `\"${rel.via}\" points at ${f.target}, not ${entity}`);",
    replace: "      else if (false) err(`${p}/via`, 'x');" },
  { name: 'block requirements are not enforced', file: 'runtime/check/steps.mjs',
    find: "        if (step[req] === undefined) err(p, `block \"${step.block}\" requires \"${req}\"`, block.summary);",
    replace: "        void req;" },
  { name: 'suggestions are dropped from error hints', file: 'runtime/check/scope.mjs',
    find: "      n.length ? `did you mean: ${n.join(', ')}? or add it to /data/${e}` : `known fields: ${known(e).join(', ')}`);",
    replace: "      `known fields: ${known(e).join(', ')}`);" },

  // The interpreter
  { name: 'required fields are not enforced on submit', file: 'runtime/interp.mjs',
    find: "      if (f.required && (v === undefined || String(v).trim() === '')) { problems.push(`${f.name} is required`); continue; }",
    replace: "      void v;" },
  { name: 'a number field accepts letters', file: 'runtime/fields.mjs',
    find: "    validate: (v, f) => {\n      if (v === undefined || v === '' || v === null) return null;\n      if (Number.isNaN(Number(v))) return `${f.name} must be a number`;\n      return Number.isInteger(Number(v)) ? null : `${f.name} must be a whole number`;\n    },",
    replace: "    validate: () => null," },
  { name: 'an enum accepts values outside its set', file: 'runtime/fields.mjs',
    find: "    validate: (v, f) => (v && !f.options.includes(String(v)) ? `${f.name} must be one of: ${f.options.join(', ')}` : null),",
    replace: "    validate: () => null," },
  { name: 'a plugin may silently replace a built-in', file: 'runtime/registry.mjs',
    find: "      if (registry[table][key]) throw new Error(", replace: "      if (false) throw new Error(" },
  { name: 'a block with a connector accepts any connector kind', file: 'runtime/check/steps.mjs',
    find: "        else if (c.kind !== block.connector) err(`${p}/connector`, `connector \"${step.connector}\" is ${c.kind}, ${step.block} needs ${block.connector}`);", replace: "" },
  { name: "a plugin block's own check never runs", file: 'runtime/check/steps.mjs',
    find: "      if (block.check) block.check(step, { err, fields, entity, graph, registry: h.registry, path: p, checkEntity, checkField });", replace: "" },
  { name: "a plugin transport's declaration is not checked", file: 'runtime/check/connectors.mjs',
    find: "    for (const [key, message, hint] of transport.validate(c)) err(`${p}/${key}`, message, hint);", replace: "" },
  { name: 'a field kind skips its own validation', file: 'runtime/interp.mjs',
    find: "      const bad = f.type.validate(v, f);\n      if (bad) problems.push(bad);", replace: "" },
  { name: 'events never fire', file: 'runtime/interp.mjs',
    find: "      runSteps(ev.do, { rowEntity: entity, id, row: snapshot, values, user, eventDepth: depth });", replace: "      void ev;" },
  { name: 'identity resolves to nothing', file: 'runtime/interp.mjs',
    find: "      const id = ctx.user ? ctx.user.id : meId;", replace: "      const id = null;" },
  { name: 'seed rows are inserted on every boot', file: 'runtime/boot.mjs',
    find: "  const remaining = new Set(seedEntities.filter((e) => !store.count(e)));",
    replace: "  const remaining = new Set(seedEntities);" },
  { name: 'the confirmation never reaches the page', file: 'runtime/routes/context.mjs',
    find: "  const ok = (to, msg) => redirect(msg ? `${to}${to.includes('?') ? '&' : '?'}ok=${encodeURIComponent(msg)}` : to);",
    replace: "  const ok = (to) => redirect(to);" },
  { name: 'a rejected form is stored anyway', file: 'runtime/routes/entity.mjs',
    find: "  if (problems.length) {\n    trace({ kind: 'rejected', entity, problems });\n    ctx.answer(400, formView(graph, store, entity, fields, submitted, 'new', problems, vc), { ok: false, status: 400, errors: problems });\n    return true;\n  }",
    replace: "  void problems;" },

  // Blocks
  { name: 'toggle only ever sets, never clears', file: 'runtime/blocks.mjs',
    find: "      store.update(entity, id, { [step.field]: row[step.field] ? 0 : 1 });",
    replace: "      store.update(entity, id, { [step.field]: 1 });" },
  { name: 'grading becomes case sensitive', file: 'runtime/blocks.mjs',
    find: "      const ok = target && String(target[step.against]).trim().toLowerCase()\n        === String(row[step.field]).trim().toLowerCase() ? 1 : 0;",
    replace: "      const ok = target && String(target[step.against]) === String(row[step.field]) ? 1 : 0;" },
  { name: 'weights are ignored when picking', file: 'runtime/blocks.mjs',
    find: "      const weights = rows.map((r) => (step.weight ? Math.max(0, Number(r[step.weight]) || 0) : 1));",
    replace: "      const weights = rows.map(() => 1);" },

  // Rendering and patching
  { name: 'html escaping is disabled', file: 'runtime/render.mjs',
    find: "const esc = (s) => String(s ?? '').replace(/[&<>\"']/g, (c) =>",
    replace: "const esc = (s) => String(s ?? '').replace(/[\\u0000]/g, (c) =>" },
  { name: 'a reference renders as its raw id', file: 'runtime/fields.mjs',
    find: "    format: (v, f, { esc, store }) => { const lbl = store.labelOf(f.target, v); return lbl ? `<a href=\"/${f.target}/${v}\">${esc(lbl)}</a>` : '—'; },",
    replace: "    format: (v, f, { esc }) => esc(v)," },
  { name: 'appending to an array overwrites its first item', file: 'runtime/patch.mjs',
    find: "    else if (last === '-' && Array.isArray(node)) node.push(op.value);",
    replace: "    else if (last === '-' && Array.isArray(node)) node[0] = op.value;" },
  // --- v2: roles, sessions, ownership ---
  { name: 'a wrong password logs in', file: 'runtime/auth.mjs',
    find: "  return probe.length === known.length && crypto.timingSafeEqual(probe, known);", replace: "  return true;" },
  { name: 'a forged session token is accepted', file: 'runtime/auth.mjs',
    find: "    if (sig.length !== expect.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expect))) return null;", replace: "" },
  { name: 'every password hashes with the same salt', file: 'runtime/auth.mjs',
    find: "  const salt = crypto.randomBytes(8).toString('hex');", replace: "  const salt = 'abcd';" },
  { name: '"own" rows are not enforced', file: 'runtime/auth.mjs',
    find: "  if (unscoped || !e.own || !row || op === 'create') return true;\n  return user ? ownedMatch(store, entity, row, e.own, user.id) : false;\n}",
    replace: "  return true;\n}" },
  { name: 'the go:* and do:* wildcards stop matching', file: 'runtime/auth.mjs',
    find: "  || (op.includes(':') && ops.includes(`${op.split(':')[0]}:*`));", replace: "  || false;" },
  { name: 'a role-gated list is visible to everyone', file: 'runtime/auth.mjs',
    find: "      return Boolean(role) && item.roles.includes(role);", replace: "      return true;" },
  { name: 'the owner is not filled from the session on create', file: 'runtime/routes/entity.mjs',
    find: "  const own = perms.ownField(user, entity);\n  if (own) values[own] = user.id;\n  const problems = interp.validateValues(entity, values);",
    replace: "  const problems = interp.validateValues(entity, values);" },
  { name: 'a list shows other people\'s rows', file: 'runtime/routes/entity.mjs',
    find: "  Object.assign(where, ownWhere(entity)); // a filter may narrow the row set, never widen it",
    replace: "" },
  { name: 'the login form accepts any password', file: 'runtime/routes/session.mjs',
    find: "    if (!found || !verifyPassword(form.password, found[graph.roles.password])) {", replace: "    if (!found) {" },
  { name: 'a download skips the permission check', file: 'runtime/routes/system.mjs',
    find: "  if (!vc.can(entity, 'view', row)) { ctx.deny(); return true; }\n  const at = path.join(filesDir, path.basename(row[fieldName]));",
    replace: "  const at = path.join(filesDir, path.basename(row[fieldName]));" },
  { name: 'entities a role cannot view stay in the menu', file: 'runtime/render.mjs',
    find: "    if (ov.hidden || !vc.can(entity, 'view')) continue;", replace: "    if (ov.hidden) continue;" },

  // --- v2: rules, transitions, actions, effects ---
  // Round 6 moved rule enforcement from interp.mjs into Store#checkRules
  // (runtime/store/rules.mjs) so a block/seed write meets it too, not only an
  // HTTP form — same defects, new file (TESTS.md's refactor convention).
  { name: 'a failing check rule is ignored', file: 'runtime/store/rules.mjs',
    find: "    if (!ok) problems.push(rule.message);", replace: "    void ok;" },
  { name: 'a unique rule never fires', file: 'runtime/store/rules.mjs',
    find: "        if (v !== undefined && v !== '' && this.exists(entity, rule.unique, v, existing?.id)) problems.push(rule.message || `${rule.unique} is already taken`);", replace: "        void v;" },
  // Round 6: rules now guard every write, not only an HTTP form (item 20) —
  // these two disable that guard specifically for a block's own insert/update
  // (interp.validateValues, and so every HTTP form test, would still be
  // green: the guard it targets is the store's, reached only by a block or a
  // seed row — see tests/interp.test.mjs's "a plugin block…"/"a built-in
  // block (db.update)…" tests, which are the only things that catch these).
  { name: 'item 20: a block\'s own insert has no path to the rule guard', file: 'runtime/store.mjs',
    find: "    // The guard: every insert meets rules here, whatever wrote it (item 20).\n    const problems = this.checkRules(entity, values, null);\n    if (problems.length) throw new Error(problems[0]);",
    replace: "" },
  { name: 'item 20: a block\'s own update has no path to the rule guard', file: 'runtime/store.mjs',
    find: "    // The guard: every update meets rules here too, against the row as it\n    // would be stored (existing row + these values) — item 20.\n    const problems = this.checkRules(entity, values, this.raw(entity, id));\n    if (problems.length) throw new Error(problems[0]);",
    replace: "" },
  { name: "uniqueness collides with the row itself", file: "runtime/store.mjs",
    find: " AND id!=${ph(2)}`;\n    return Boolean(this.drv.get(sql, [v, Number(excludeId ?? 0)]));",
    replace: "`;\n    return Boolean(this.drv.get(sql, [v]));" },
  { name: 'a transition ignores the status it starts from', file: 'runtime/render.mjs',
    find: "    if (from && !from.includes(row[st.field])) return false;", replace: "" },
  { name: 'a transition ignores who may take it', file: 'runtime/render.mjs',
    find: "    if (t.by && !t.by.includes(vc.role)) return false;", replace: "" },
  { name: 'the fields a transition asks for are optional', file: 'runtime/routes/rows.mjs',
    find: "  for (const f of t.fields || []) if (values[f] === undefined || String(values[f]).trim() === '') problems.push(`${f} is required`);", replace: "" },
  { name: 'a refused block commits what it did before failing', file: 'runtime/driver/sqlite.mjs',
    find: "    catch (e) { drv.exec('ROLLBACK'); throw e; }", replace: "    catch (e) { drv.exec('COMMIT'); throw e; }" },
  { name: 'S1: the driver leaves a failed transaction open (no rollback at all)', file: 'runtime/driver/sqlite.mjs',
    find: "    catch (e) { drv.exec('ROLLBACK'); throw e; }", replace: "    catch (e) { throw e; }" },
  { name: 'S1: the driver never commits a transaction that returned normally', file: 'runtime/driver/sqlite.mjs',
    find: "const out = fn(); drv.exec('COMMIT'); return out;", replace: "const out = fn(); return out;" },
  { name: 'S1: run() reports the changed-row count as the inserted id', file: 'runtime/driver/sqlite.mjs',
    find: "lastId: Number(r.lastInsertRowid)", replace: "lastId: Number(r.changes)" },
  { name: 'S1: run() reports no changed rows', file: 'runtime/driver/sqlite.mjs',
    find: "changes: Number(r.changes),", replace: "changes: 0," },
  { name: 'S1: the statement cache never evicts (grows without bound)', file: 'runtime/driver/sqlite.mjs',
    find: "    if (cache.size > CACHE_MAX) cache.delete(cache.keys().next().value);", replace: "    void CACHE_MAX;" },
  { name: 'S1: the statement cache evicts the most recently used entry instead of the oldest', file: 'runtime/driver/sqlite.mjs',
    find: "if (hit) { cache.delete(sql); cache.set(sql, hit); return hit; }", replace: "if (hit) return hit;" },
  { name: 'S1: the statement cache is bypassed (a fresh statement every call)', file: 'runtime/driver/sqlite.mjs',
    find: "    const hit = cache.get(sql);", replace: "    const hit = null;" },
  { name: 'S1: an uncached call ({ cache: false }) fills the cache anyway', file: 'runtime/driver/sqlite.mjs',
    find: "if (opts?.cache === false) return db.prepare(sql);", replace: "if (false) return db.prepare(sql);" },
  { name: 'S1: the query hook is never called', file: 'runtime/driver/sqlite.mjs',
    find: "    if (drv.onQuery) drv.onQuery(sql, opts);\n    if (opts?.cache", replace: "    if (opts?.cache" },
  { name: 'the outbox is never flushed after a commit', file: 'runtime/interp.mjs',
    find: "    const out = store.transaction(fn);\n    await flush(store, graph, { fetchImpl, trace, registry });\n    return out;", replace: "    return store.transaction(fn);" },
  { name: 'a non-2xx answer counts as delivered', file: 'runtime/connectors/engine.mjs',
    find: "const patch = { code: res.status, status: res.ok ? 'sent' : 'failed', error: res.ok ? null : `HTTP ${res.status}` };",
    replace: "const patch = { code: res.status, status: 'sent', error: null };" },
  { name: "the claim does not require the row to be queued", file: "runtime/store/state.mjs",
    find: "AND (${q('status')}='queued' OR (${q('status')}='sending' AND ${q('claimedAt')}<=${ph(4)}))",
    replace: "AND (1=1 OR (${q('status')}='sending' AND ${q('claimedAt')}<=${ph(4)}))" },
  { name: 'the claim ignores how many rows it changed', file: 'runtime/store/state.mjs',
    find: "Number(id), now - leaseMs]).changes === 1;", replace: "Number(id), now - leaseMs]).changes >= 0;" },
  { name: "the claim lease comparison is inverted", file: "runtime/store/state.mjs",
    find: "${q('claimedAt')}<=${ph(4)}))`",
    replace: "${q('claimedAt')}>=${ph(4)}))`" },
  { name: 'flush delivers rows it did not claim', file: 'runtime/outbox.mjs',
    find: "    if (store.outboxClaim(row.id, claimedAt, leaseMs)) out.push(", replace: "    if (store.outboxClaim(row.id, claimedAt, leaseMs) || true) out.push(" },
  { name: "the final write ignores the claim it was made under", file: "runtime/store/state.mjs",
    find: "${q('claimedAt')}=${ph(n)} AND ${q('status')}='sending'`",
    replace: "(${q('claimedAt')}=${ph(n)} OR 1=1) AND ${q('status')}='sending'`" },
  { name: "the final write ignores that the row is still sending", file: "runtime/store/state.mjs",
    find: "=${ph(n)} AND ${q('status')}='sending'`",
    replace: "=${ph(n)} AND 1=1`" },
  { name: 'a delivery that lost its claim is still reported as a result', file: 'runtime/outbox.mjs',
    find: "claimedAt !== null && !store.outboxFinish(", replace: "claimedAt !== null && store.outboxFinish(" },
  { name: "flush never picks up a row whose lease ran out", file: "runtime/store/state.mjs",
    find: "${q('claimedAt')}<=${ph(1)}) ORDER BY id ASC",
    replace: "${q('claimedAt')}<=${ph(1)} AND 1=0) ORDER BY id ASC" },
  { name: 'an old outbox table is not upgraded', file: 'runtime/store/migrate.mjs',
    find: "for (const [name, type] of OUTBOX_LATER) if (!live.includes(name)) this.drv.addColumn", replace: "for (const [name, type] of OUTBOX_LATER) if (false) this.drv.addColumn" },
  { name: 'attempts are never counted', file: 'runtime/outbox.mjs',
    find: "  const patch = { attempts: (row.attempts || 0) + 1 };", replace: "  const patch = { attempts: 1 };" },
  { name: 'updated events never fire', file: 'runtime/routes/entity.mjs',
    find: "      interp.fireEvents('updated', entity, id, submitted, user);", replace: "" },
  { name: 'db.adjust ignores its floor', file: 'runtime/blocks.mjs',
    find: "      if (step.min !== undefined && next < step.min) throw new Error(step.message || `${target}.${step.field} cannot go below ${step.min}`);", replace: "" },
  { name: 'db.adjust moves money in minor units', file: 'runtime/blocks.mjs',
    find: "      if (f.kind === 'money') by = toMinor(by);", replace: "" },
  { name: 'db.ensure always creates', file: 'runtime/blocks.mjs',
    find: "      if (hit) return { found: hit, made: false };", replace: "" },
  { name: 'db.each ignores its where', file: 'runtime/blocks.mjs',
    find: "      const rows = store.list(step.from, { where: resolve(step.where || {}), sort: { field: 'id', dir: 'asc' } });",
    replace: "      const rows = store.list(step.from, { sort: { field: 'id', dir: 'asc' } });" },
  { name: 'an empty upload replaces the stored file', file: 'runtime/interp.mjs',
    find: "      if (f.type.upload && submitted[f.name] === '' && !f.required) delete submitted[f.name];", replace: "" },
  { name: 'the flash is lost on the home redirect', file: 'runtime/routes/views.mjs',
    find: "  const keep = (to) => (flash ? `${to}${to.includes('?') ? '&' : '?'}ok=${encodeURIComponent(flash)}` : to);", replace: "  const keep = (to) => to;" },

  { name: 'a created row replaces the row the action runs on', file: 'runtime/interp.mjs',
    find: "      const { id: createdId, ...rest } = out;\n      Object.assign(ctx, rest);", replace: "      const createdId = out.id;\n      Object.assign(ctx, out);" },

  { name: 'a related table shows rows the viewer does not own', file: 'runtime/render/detail.mjs',
    find: "where: { [rel.via]: row.id, ...vc.ownWhere(rel.entity) }", replace: "where: { [rel.via]: row.id }" },
  { name: '@me.field ignores the field', file: 'runtime/interp.mjs',
    find: "      if (!rest.length) return id;\n      const ent = graph.roles?.entity || graph.identity?.entity;", replace: "      return id;\n      const ent = graph.roles?.entity || graph.identity?.entity;" },
  { name: 'a form landed on loses the flash', file: 'runtime/routes/entity.mjs',
    find: "send(200, formView(graph, store, entity, fields, {}, 'new', [], vc, flash))", replace: "send(200, formView(graph, store, entity, fields, {}, 'new', [], vc))" },
  { name: 'aggregate bodies are resolved against the outer entity', file: 'runtime/check/data.mjs',
    find: "          } else if (n.t === 'agg') { if (entities.includes(n.entity) && n.body) walk(n.body, n.entity, e); }", replace: "          } else if (n.t === 'agg') { if (entities.includes(n.entity) && n.body) walk(n.body, e, e); }" },

  { name: 'a refusal inside a created event is a crash', file: 'runtime/routes/entity.mjs',
    find: "  } catch (e) {\n    trace({ kind: 'refused', entity, message: e.message });\n    ctx.answer(400, formView(graph, store, entity, fields, submitted, 'new', [e.message], vc), { ok: false, status: 400, errors: [e.message] });\n    return true;\n  }",
    replace: "  } catch (e) { throw e; }" },

  // --- round 3: lists, export, correlated aggregates, dates, images ---
  { name: 'sorting ignores the direction', file: 'runtime/routes/context.mjs',
    find: "return { field, dir: url.searchParams.get('dir') === 'desc' ? 'desc' : 'asc' };", replace: "return { field, dir: 'asc' };" },
  { name: 'paging shows every row on every page', file: 'runtime/store/query.mjs',
    find: "  const raw = this.listRawPage(entity, opts, pageSize, (at - 1) * pageSize);",
    replace: "  const raw = this.listRawPage(entity, opts, total, 0);" },
  { name: 'paging shows every row on every page (the full-scan fallback path)', file: 'runtime/store/query.mjs',
    find: "    return { rows: rows.slice((at - 1) * pageSize, at * pageSize), total: rows.length, page: at, pages };",
    replace: "    return { rows, total: rows.length, page: at, pages };" },
  { name: 'csv cells are never quoted', file: 'runtime/render.mjs',
    find: "return /[\",\\n\\r]/.test(s) ? `\"${s.replace(/\"/g, '\"\"')}\"` : s;", replace: "return s;" },
  { name: 'a correlated aggregate reads the child instead of the outer row', file: 'runtime/expr.mjs',
    find: "        const rows = ctx.rows(n.entity, n.via).map((r) => ({ get: (p) => (p[0] === 'row' && p.length > 1 ? ctx.get(p.slice(1)) : r.get(p)), rows: (e, v) => r.rows(e, v), clock }));",
    replace: "        const rows = ctx.rows(n.entity, n.via);" },
  { name: 'addDays subtracts', file: 'runtime/functions.mjs',
    find: "d.setUTCDate(d.getUTCDate() + Math.round(a[1]));", replace: "d.setUTCDate(d.getUTCDate() - Math.round(a[1]));" },
  { name: 'R12: a product of money is left as the raw double (3 * 0.1 > 0.3)', file: 'runtime/expr.mjs',
    find: "case '*': return exact(a * b);", replace: "case '*': return a * b;" },
  { name: 'max over dates picks the earliest', file: 'runtime/expr.mjs',
    find: "        if (typeof vals[0] === 'string') return vals.reduce((a, b) => (n.fn === 'min' ? (b < a ? b : a) : (b > a ? b : a)));",
    replace: "        if (typeof vals[0] === 'string') return vals.reduce((a, b) => (b < a ? b : a));" },
  { name: 'an image is served as a download even inline', file: 'runtime/routes/system.mjs',
    find: "  const inline = url.searchParams.get('inline') === '1' && mime;", replace: "  const inline = false;" },
  { name: '{created} in an after path is dropped', file: 'runtime/interp.mjs',
    find: "    if (k in extra) return String(extra[k] ?? '');", replace: "" },
  { name: 'a where on id matches nothing', file: 'runtime/store/query.mjs',
    find: "    const f = field === 'id' ? { kind: 'int', type: this.registry.fields.int } : this.field(entity, field);",
    replace: "    const f = this.field(entity, field);" },

  // --- v2: expressions, money, derived fields ---
  { name: 'a comparison forgets the additive level', file: 'runtime/expr.mjs',
    find: "const parseCmp = (st) => {\n  const a = parseAdd(st);", replace: "const parseCmp = (st) => {\n  const a = parseMul(st);" },
  { name: 'null poisons arithmetic instead of propagating', file: 'runtime/expr.mjs',
    find: "        if (a == null || b == null) return n.op === '<' || n.op === '<=' || n.op === '>' || n.op === '>=' ? false : null;", replace: "" },
  { name: 'days() counts hours', file: 'runtime/functions.mjs',
    find: "  const d = new Date(`${String(v).slice(0, 10)}T00:00:00Z`);",
    replace: "  const d = new Date(String(v).length === 10 ? `${v}T00:00:00Z` : v);" },
  { name: 'a sum counts nulls as zero rows', file: 'runtime/expr.mjs',
    find: "        const vals = rows.map((r) => evaluate(n.body, r, functions)).filter((v) => v !== null && v !== undefined);", replace: "        const vals = rows.map((r) => evaluate(n.body, r, functions));" },
  { name: 'money is stored in major units', file: 'runtime/fields.mjs',
    find: "  return Math.sign(n) * Math.round(Number((Math.abs(n) * 100).toFixed(6)));",
    replace: "  return Math.round(n);" },
  { name: 'an expression reads money in minor units', file: 'runtime/store/ctx.mjs',
    find: "    const v = toExpr(f, f.derive ? store.derived(entity, row, f, this.stack, cache, this.clock) : row[head]);",
    replace: "    const v = f.derive ? store.derived(entity, row, f, this.stack, cache, this.clock) : row[head];" },
  { name: 'derived fields are not computed on read', file: 'runtime/store.mjs',
    find: "    for (const f of this.fields[entity]) if (f.derive) out[f.name] = this.derived(entity, row, f, [], cache);", replace: "" },
  { name: 'a range on a derived field compares in the wrong units', file: 'runtime/store/query.mjs',
    find: "  const c = (x) => (f ? coerce(f, x) : x);", replace: "  const c = (x) => x;" },
  { name: 'gte means gt', file: 'runtime/store/query.mjs',
    find: "const OPS = { gte: '>=', lte: '<=', gt: '>', lt: '<', ne: '!=' };", replace: "const OPS = { gte: '>', lte: '<=', gt: '>', lt: '<', ne: '!=' };" },
  { name: "month buckets are whole dates", file: "runtime/driver/dialects.mjs",
    find: "const UNITS = { day: '%Y-%m-%d', month: '%Y-%m', year: '%Y' };",
    replace: "const UNITS = { day: '%Y-%m-%d', month: '%Y-%m-%d', year: '%Y' };" },
  { name: 'a password column passes the checker', file: 'runtime/check/scope.mjs',
    find: "    if (secret && fields[e][f].type.secret) { err(path, `\"${f}\" is a ${fields[e][f].kind} and is never shown`, 'drop it from the columns'); return false; }", replace: "" },
  { name: 'money renders in minor units', file: 'runtime/fields.mjs',
    find: "export const formatMoney = (v) => (v === null || v === undefined ? '' : (v / 100).toFixed(2));", replace: "export const formatMoney = (v) => (v === null || v === undefined ? '' : String(v));" },

  // --- v2: the checker ---
  { name: 'unreachable statuses pass the checker', file: 'runtime/check/states.mjs',
    find: "    if (dead.length) err(`${p}/transitions`, `no transition leads to: ${dead.join(', ')}`, `add a transition \"to\" each, or drop it from ${entity}.${st.field}`);", replace: "" },
  { name: 'unknown operations pass the role matrix', file: 'runtime/check/roles.mjs',
    find: "    err(path, `unknown operation \"${op}\"`,", replace: "    return err(null, `unknown operation \"${op}\"`," },
  { name: 'a derived cycle passes the checker', file: 'runtime/check/data.mjs',
    find: "  if (found) err(`/data/${found.key.replace('.', '/')}`, `derived fields depend on each other: ${found.c.join(' → ')}`, 'one of them has to be stored');", replace: "" },
  { name: 'bad expressions pass the checker', file: 'runtime/check/scope.mjs',
    find: "    catch (e) { err(path, `bad expression: ${e.message}`, `expression: ${src}`); return null; }", replace: "    catch (e) { return null; }" },
  { name: 'unknown top-level nodes pass the checker', file: 'runtime/check/basics.mjs',
    find: "    if (!TOP.includes(k)) {", replace: "    if (false) {" },
  { name: 'an unknown @reference passes the checker', file: 'runtime/check/scope.mjs',
    find: "      return err(path, `unknown reference \"${v}\"`,", replace: "      return void err(null, `unknown reference \"${v}\"`," },

  // --- R3: the refactor's own new gates and fixes ---
  { name: 'a throwing rule passes instead of refusing the write (fail-open regression)', file: 'runtime/store/rules.mjs',
    find: "    catch (e) { this.trace({ kind: 'error', message: `rule ${rule.check}: ${e.message}` }); problems.push(rule.message); continue; }",
    replace: "    catch (e) { this.trace({ kind: 'error', message: `rule ${rule.check}: ${e.message}` }); ok = true; }" },
  { name: 'anonymous access is never asked to sign in', file: 'runtime/server.mjs',
    find: "  if (ctx.perms.enabled && !ctx.role) { ctx.deny('Please sign in.'); return; }", replace: "" },

  // --- R2: widgets, JSON answers, charts, schedule ---
  { name: 'a secret field reaches a JSON answer', file: 'runtime/render.mjs',
    find: "  for (const f of fields) if (!f.type.secret) out[f.name] = mayReadField(store.graph, entity, f.name, row, vc) ? toJSON(row[f.name], f) : null;",
    replace: "  for (const f of fields) out[f.name] = toJSON(row[f.name], f);" },
  { name: 'a denied JSON request gets an HTML/redirect answer instead of a JSON body', file: 'runtime/routes/context.mjs',
    find: "    if (wantsJSON) return sendJson(403, { ok: false, status: 403, errors: [message || 'You are not allowed to do this.'] });", replace: "" },
  { name: 'anyone may run a schedule by hand, not only an operator', file: 'runtime/routes/schedule.mjs',
    find: "  if (!vc.outbox) { ctx.deny('Only an operator may run a schedule by hand.'); return true; }", replace: "" },
  { name: "a chart's axis label shows raw storage units instead of the money-formatted value", file: 'runtime/render/dashboard.mjs',
    find: "  const maxDisplay = metricValue(store, chart.entity, chart.metric.fn === 'count' ? null : chart.metric.field, max);",
    replace: "  const maxDisplay = String(max);" },

  // --- this round: 13 format gaps plus two bugs the app agents found ---
  { name: 'item 1: a one-hop "own" path never matches (a note is never one\'s own through its profile)', file: 'runtime/auth.mjs',
    find: "  const parent = store.raw(f.target, refId);\n  return parent ? String(parent[subField]) === String(userId) : false;",
    replace: "  return false;" },
  { name: 'item 2: a "by"-gated row action button ignores "by" and asks the matrix alone again', file: 'runtime/render.mjs',
    find: "    if (!(act ? mayRunAction(vc, entity, act, r) : vc.can(entity, `do:${a}`, r))) return '';",
    replace: "    if (!vc.can(entity, `do:${a}`, r)) return '';" },
  { name: "item 3: a related fill can't read the parent row again (@row.* resolves to nothing)", file: 'runtime/routes/rows.mjs',
    find: "  const fillRow = interp.resolve({ user, values: submitted, rowEntity: entity, id, row });",
    replace: "  const fillRow = interp.resolve({ user, values: submitted });" },
  { name: 'item 4: a compound unique rule checks the submitted values instead of the stored row, and misses an untouched field', file: 'runtime/store/rules.mjs',
    find: "      if (known && this.existsAll(entity, names, probe, existing?.id)) problems.push(rule.message || `${names.join(' + ')} must be unique together`);",
    replace: "      if (known && this.existsAll(entity, names, values, existing?.id)) problems.push(rule.message || `${names.join(' + ')} must be unique together`);" },
  { name: 'item 5: db.set ignores "entity" and updates the current row instead', file: 'runtime/blocks.mjs',
    find: "    run: ({ store, step, resolve }) => { store.update(step.entity, resolve({ v: step.id }).v, resolve(step.set)); return {}; },",
    replace: "    run: ({ store, entity, step, resolve }) => { store.update(entity, resolve({ v: step.id }).v, resolve(step.set)); return {}; }," },
  { name: 'item 6: an embedded page form ignores the "create" permission', file: 'runtime/render/pages.mjs',
    find: "    if (!vc.can(s.form, 'create')) return '';",
    replace: "" },
  { name: 'item 7: /search ignores per-entity view permission', file: 'runtime/routes/views.mjs',
    find: "  const results = graph.search.entities.filter((e) => vc.can(e, 'view')).map((entity) => {",
    replace: "  const results = graph.search.entities.map((entity) => {" },
  { name: 'item 8: a "viewed" event never fires, even when one is declared', file: 'runtime/routes/entity.mjs',
    find: "  if (!(graph.events || []).some((ev) => ev.on === `${entity}.viewed`)) return row;",
    replace: "  return row;" },
  { name: "item 9: hours() answers in the wrong unit (minutes' divisor)", file: 'runtime/functions.mjs',
    find: "    run: (a) => { const x = toInstant(a[0]), y = toInstant(a[1]); return x && y ? Math.round((+x - +y) / hourMs * 1e6) / 1e6 : null; } },",
    replace: "    run: (a) => { const x = toInstant(a[0]), y = toInstant(a[1]); return x && y ? Math.round((+x - +y) / minuteMs * 1e6) / 1e6 : null; } }," },
  { name: "item 10: a role's byRole field list is never consulted", file: 'runtime/render/form.mjs',
    find: "export const formFieldsFor = (ov, role) => ov.byRole?.[role]?.fields ?? ov.fields;",
    replace: "export const formFieldsFor = (ov, role) => ov.fields;" },
  { name: 'item 11: a seeded file is linked without ever being copied into files/', file: 'runtime/boot.mjs',
    find: "    fs.copyFileSync(path.join(appDir, v.from), path.join(filesDir, name));",
    replace: "" },
  { name: 'item 12: a derived field may not read "id" any more', file: 'runtime/check/scope.mjs',
    find: "      if (head === 'id') {\n        if (rest.length) throw new Error(`${entity}.id is a number, cannot read .${rest[0]} of it`);\n        return 'number';\n      }",
    replace: "" },
  { name: 'item 14: a row a block creates never fires its own "created" event', file: 'runtime/interp.mjs',
    find: "        fireCreated: fireCreatedFor(ctx),",
    replace: "        fireCreated: () => {}," },
  { name: 'item 14: a cycle of "created" events never refuses, it just recurses', file: 'runtime/interp.mjs',
    find: '    if (depth > MAX_EVENT_DEPTH) throw new Error(`too many nested "${trigger}" events — check for a cycle through ${entity}.${trigger}`);',
    replace: '' },
  { name: "item 15: Entity.form's confirm/confirmEdit stop interpolating the written row", file: 'runtime/routes/entity.mjs',
    find: "  const flash = formOv.confirm ? interp.interpolate(formOv.confirm, { rowEntity: entity, row: createdRow, id, created: id }) : `${label(entity)} saved successfully`;",
    replace: "  const flash = formOv.confirm || `${label(entity)} saved successfully`;" },

  // --- more gaps confirmed by app agents, addressed after 1-15 ---
  { name: "item 16: \"ne: null\" is silently dropped again instead of meaning IS NOT NULL", file: "runtime/store/query.mjs",
    find: "clauses.push(`${q(field)} IS NOT NULL`); continue; }\n        if (v === undefined || v === '' || v === null) continue;",
    replace: "clauses.push(`${q(field)} IS NOT NULL`); continue; }\n        if (true) continue;" },
  { name: 'item 17: a "private" field is never redacted, from anyone, anywhere', file: 'runtime/render.mjs',
    find: "function mayReadField(graph, entity, field, row, vc = anyone) {\n  const owner = graph?.override?.[`${entity}.detail`]?.private?.[field];\n  if (!owner || !row) return true;\n  if (vc.isAdmin) return true;\n  return vc.user ? String(row[owner]) === String(vc.user.id) : false;\n}",
    replace: "function mayReadField() { return true; }" },
  { name: 'item 18: a widget prop never resolves "@row.field" server-side', file: 'runtime/render.mjs',
    find: "  for (const [k, v] of Object.entries(props)) if (typeof v === 'string' && v.startsWith('@row.')) props[k] = row ? row[v.slice(5)] : null;",
    replace: "" },
  { name: "item 19: a row action's declared fields are never required", file: 'runtime/routes/rows.mjs',
    find: "  if (action.fields?.length) {\n    // Item 19: a row action's declared fields are typed and required, exactly\n    // like a transition's own `fields`.\n    const problems = interp.validateValues(entity, submitted, { partial: true, existing: row });\n    for (const f of action.fields) if (submitted[f] === undefined || String(submitted[f]).trim() === '') problems.push(`${f} is required`);\n    if (problems.length) { ctx.answer(400, detailView(graph, store, entity, fields, row, problems.join('; '), vc), { ok: false, status: 400, errors: problems }); return true; }\n  }",
    replace: "" },

  // --- round 7: indexes, page-before-hydrate, batched aggregates, prepared cache ---
  { name: 'round 7: a ref column never gets an index', file: 'runtime/store/migrate.mjs',
    find: "  for (const f of store.fields[entity] || []) if (f.kind === 'ref') add([f.name]);",
    replace: "" },
  { name: 'round 7: a no-longer-desired index is never dropped, only ever added', file: 'runtime/store/migrate.mjs',
    find: "    if (keep.has(name)) continue;\n    this.drv.dropIndex(name);",
    replace: "    if (true) continue;\n    this.drv.dropIndex(name);" },
  { name: "round 7: the batched child fetch's IN-list is never coerced to match a ref column's TEXT storage, so every group comes up empty", file: 'runtime/store/query.mjs',
    find: "    const vals = ids.slice(i, i + IN_CHUNK).map(String);",
    replace: "    const vals = ids.slice(i, i + IN_CHUNK);" },
  { name: 'round 7: a batched aggregate groups children by the wrong (uncoerced) key, so every group comes up empty (moved to store/hydrate.mjs in R8)', file: 'runtime/store/hydrate.mjs',
    find: "      const grouped = new Map(ids.map((id) => [String(id), []]));\n      for (const r of rows) grouped.get(String(r[via]))?.push(r);",
    replace: "      const grouped = new Map(ids.map((id) => [id, []]));\n      for (const r of rows) grouped.get(r[via])?.push(r);" },
  { name: 'round 7: a nested aggregate (a chain of two or more hops) never prefetches past the first level (moved to store/hydrate.mjs in R8)', file: 'runtime/store/hydrate.mjs',
    find: "      const childIds = rows.map((r) => r.id);\n      if (childIds.length) this.buildAggCache(agg.entity, childIds, cache, seen);",
    replace: "" },
  { name: 'round 7: a page always takes the cheap SQL-count-and-limit path, even when a derived sort or an in-memory where would give the wrong page', file: 'runtime/store/query.mjs',
    find: "  if (later.length || sortField?.derive) {",
    replace: "  if (false) {" },
  { name: "round 7: hydrating a page never uses the batch cache — back to one query per row per aggregate (moved to store/hydrate.mjs in R8)", file: 'runtime/store/hydrate.mjs',
    find: "function hydratePageChunk(entity, rows) {\n  const cache = this.buildAggCache(entity, rows.map((r) => r.id));\n  return rows.map((r) => this.hydrate(entity, r, cache));\n}",
    replace: "function hydratePageChunk(entity, rows) { return rows.map((r) => this.hydrate(entity, r)); }" },

  // --- round 7, orchestrator review: item A/B/C fixes ---
  { name: 'round 7 item A: labelOf hydrates the whole target row again instead of reading only the label field', file: 'runtime/store/query.mjs',
    find: "  const v = f.derive ? this.derived(entity, row, f) : row[lf];",
    replace: "  const v = this.hydrate(entity, row)[lf];" },
  { name: 'round 7 item B: the IN-list is never chunked, so a big enough prefetch can exceed the bound-parameter limit', file: 'runtime/store/query.mjs',
    find: 'const IN_CHUNK = 5000;', replace: 'const IN_CHUNK = Infinity;' },
  { name: "round 7 item C: a batched child fetch drops the unbatched path's own order (ORDER BY id DESC), so a float sum can round differently", file: "runtime/store/query.mjs",
    find: "IN (${phs(vals.length)}) ORDER BY id DESC`",
    replace: "IN (${phs(vals.length)})`" },

  // --- round 8: SQL-compiled aggregates (runtime/store/aggsql.mjs) and chunked hydration ---
  { name: 'R8 item 1: a fractional literal compiles too, reintroducing the float-summation-order risk the design avoids', file: 'runtime/store/aggexpr.mjs',
    find: "  if (n.t === 'num') return Number.isSafeInteger(n.v) ? int(String(n.v)) : null;",
    replace: "  if (n.t === 'num') return int(String(n.v));" },
  { name: 'R8 item 1: division compiles too (SQLite integer division truncates, and a per-row float would reopen the summation-order risk)', file: 'runtime/store/aggexpr.mjs',
    find: "  if (n.op !== '+' && n.op !== '-' && n.op !== '*') return null; // division and comparisons are never a value",
    replace: "  if (n.op === '=') return null;" },
  { name: "R8 item 1: an ordering comparison with a null operand leaks SQL NULL instead of the definite false runtime/expr.mjs always returns", file: "runtime/store/aggexpr.mjs",
    find: "WHEN ${as} ${n.op} ${bs} THEN 1 ELSE 0 END)`;",
    replace: "WHEN ${as} ${n.op} ${bs} THEN 1 END)`;" },
  { name: 'R8 item 1: sum/count of an empty batched group comes back null instead of 0 (runtime/expr.mjs\'s own reduce(…, 0))', file: 'runtime/store/aggsql.mjs',
    find: "  const empty = compiled.fn === 'sum' || compiled.fn === 'count' ? 0 : null;",
    replace: '  const empty = null;' },
  { name: 'R8 item 1: a compiled sum is never converted out of its minor-unit scale', file: 'runtime/store/aggsql.mjs',
    find: "  if (c.fn === 'sum') return exact(Number(row.v ?? 0) / c.scale);",
    replace: "  if (c.fn === 'sum') return exact(Number(row.v ?? 0));" },
  { name: 'R8 item 1: a compiled avg is never converted out of its minor-unit scale', file: 'runtime/store/aggsql.mjs',
    find: "  if (c.fn === 'avg') { const n = Number(row.c ?? 0); return n ? exact(Number(row.v ?? 0) / c.scale / n) : null; }",
    replace: "  if (c.fn === 'avg') { const n = Number(row.c ?? 0); return n ? exact(Number(row.v ?? 0) / n) : null; }" },
  { name: 'R8 item 1: a single-row (uncached) compilable aggregate silently returns undefined instead of running its own query', file: 'runtime/store/hydrate.mjs',
    find: '  const hit = batch?.get(String(row.id));\n  return hit !== undefined ? hit : runAggOne(this, compiled, row.id, clock);',
    replace: '  return batch?.get(String(row.id));' },
  { name: 'R8 item 2: hydratePage no longer chunks a big page, so a full CSV export holds every batched child in memory for the whole request again', file: 'runtime/store/hydrate.mjs',
    find: '  if (rows.length <= HYDRATE_CHUNK) return hydratePageChunk.call(this, entity, rows);\n  const out = [];\n  for (let i = 0; i < rows.length; i += HYDRATE_CHUNK) out.push(...hydratePageChunk.call(this, entity, rows.slice(i, i + HYDRATE_CHUNK)));\n  return out;',
    replace: '  return hydratePageChunk.call(this, entity, rows);' },
  // --- round 9: derived fields, derived aggregates and dates in an aggregate body ---
  { name: 'R9 item 1: a money*money derived field is inlined without the cent rounding it would need', file: 'runtime/store/aggexpr.mjs',
    find: "  return s === 1 ? { sql: `(${v.sql} * 100)`, scale: 100 } : s === 100 ? v : null;",
    replace: "  return s === 1 ? { sql: `(${v.sql} * 100)`, scale: 100 } : v;" },
  { name: 'R9 item 1: an int derived from a money expression is inlined although Math.round of the major value is not the minor integer', file: 'runtime/store/aggexpr.mjs',
    find: "  if (f.kind === 'int') return s === 1 ? v : null;", replace: "  if (f.kind === 'int') return v;" },
  { name: 'R9 item 1: derived fields are inlined without any bound on how deep they nest', file: 'runtime/store/aggexpr.mjs',
    find: 'const MAX_STACK = 8;', replace: 'const MAX_STACK = Infinity;' },
  { name: 'R9 item 1: a derived-field expression that multiplies at every level may make the compiler exponential', file: 'runtime/store/aggexpr.mjs',
    find: 'export const MAX_EXPANSIONS = 200;', replace: 'export const MAX_EXPANSIONS = Infinity;' },
  { name: 'R9 item 2: subqueries nest without limit', file: 'runtime/store/aggexpr.mjs',
    find: 'const MAX_DEPTH = 5;', replace: 'const MAX_DEPTH = Infinity;' },
  { name: 'R9 item 2: the inner sum of an order with no items is NULL instead of 0 (evaluate()\'s reduce(…, 0))', file: 'runtime/store/aggexpr.mjs',
    find: "  if (n.fn === 'sum') return { sql: `COALESCE((SELECT SUM(${b.exprSQL}) ${from}), 0)`, scale: b.scale };",
    replace: "  if (n.fn === 'sum') return { sql: `(SELECT SUM(${b.exprSQL}) ${from})`, scale: b.scale };" },
  { name: "R9 item 2: the correlated join compares a TEXT ref column with an INTEGER id, which cannot use the ref index (a scan per parent row)", file: "runtime/store/aggexpr.mjs",
    find: "= CAST(t${cx.depth}.${q('id')} AS TEXT)`",
    replace: "= t${cx.depth}.${q('id')}`" },
  { name: 'R9 item 2: an inner avg (a fraction, evaluate() rounds it) compiles as a subquery', file: 'runtime/store/aggexpr.mjs',
    find: "  if (!b || n.fn === 'avg') return null;", replace: "  if (!b) return null;" },
  { name: 'R9/R12: + - * accept a scale beyond the 6 decimals exact() rounds to', file: 'runtime/store/aggexpr.mjs',
    find: '  if (scale > MAX_SCALE) return null;', replace: '  if (false) return null;' },
  { name: 'R9 item 3: a date compares with a number', file: 'runtime/store/aggexpr.mjs',
    find: 'const agree = (a, b) => (a.text ? !isNum(b) : b.text ? !isNum(a) : true);', replace: 'const agree = () => true;' },
  { name: 'R9 item 3: any string literal compiles, not only an ISO date/time', file: 'runtime/store/aggexpr.mjs',
    find: "DATE.test(n.v) || TIME.test(n.v) ? {", replace: "true ? {" },
  { name: 'R9 item 3: a sum over a date compiles', file: 'runtime/store/aggexpr.mjs',
    find: "(v.text && (node.fn === 'sum' || node.fn === 'avg'))", replace: 'false' },
  { name: 'R9 item 3: max/min over a date is answered as a number', file: 'runtime/store/aggsql.mjs',
    find: '  return c.text ? row.v : Number(row.v) / c.scale;', replace: '  return Number(row.v) / c.scale;' },
  { name: 'R9 item 3: `today` is bound with its time part (the clock as an ISO timestamp)', file: 'runtime/store/aggsql.mjs',
    find: "p === '$today' ? clock.toISOString().slice(0, 10) : clock.toISOString()", replace: 'clock.toISOString()' },
  { name: 'R9 item 3: a batch computed for one clock is read by an evaluation on another', file: 'runtime/store/hydrate.mjs',
    find: 'compiled.params.length && clock !== cache?.clock ? undefined :', replace: 'false ? undefined :' },
  { name: 'R9 item 3: an integer beyond SQLite/JS range throws out of a compiled aggregate instead of declining to the JS path', file: 'runtime/store/aggsql.mjs',
    find: '    if (OVERFLOW.test(String(e?.message))) return undefined;', replace: '    if (false) return undefined;' },
  { name: 'R9: a derived field reached from an expression reads its own clock instead of the evaluation\'s', file: 'runtime/store/ctx.mjs',
    find: "store.derived(entity, row, f, this.stack, cache, this.clock) : row[head]);", replace: "store.derived(entity, row, f, this.stack, cache) : row[head]);" },
  { name: 'R9: the child rows of an aggregate do not inherit the evaluation\'s clock', file: 'runtime/store/ctx.mjs',
    find: "return raws.map((r) => store.ctx(child, r, this.stack, { cache, clock: this.clock }));", replace: "return raws.map((r) => store.ctx(child, r, this.stack, { cache }));" },
  // --- round 8: dashboard JSON money ---
  { name: "round 8: a dashboard JSON card/table/chart money aggregate answers raw minor units instead of major units", file: 'runtime/routes/views.mjs',
    find: "  return f?.kind === 'money' ? Number(formatMoney(Math.round(v))) : v;",
    replace: "  return v;" },

  // --- S2: portable SQL and dialect hooks (runtime/driver/dialects.mjs) ---
  { name: "S2: LIKE escapes the escape character too, so a typed backslash is a backslash", file: "runtime/driver/dialects.mjs",
    find: "const escapeLike = (v) => String(v).replace(/[\\\\%_]/g,",
    replace: "const escapeLike = (v) => String(v).replace(/[%_]/g," },
  { name: "S2: LIKE stops escaping % and _, so \"50%\" is \"50 and anything\"", file: "runtime/driver/dialects.mjs",
    find: "(c) => `\\\\${c}`);\nconst bytes",
    replace: "(c) => c);\nconst bytes" },
  { name: "S2: the PostgreSQL month bucket keeps the whole date", file: "runtime/driver/dialects.mjs",
    find: "const LENGTHS = { day: 10, month: 7, year: 4 };",
    replace: "const LENGTHS = { day: 10, month: 10, year: 4 };" },
  { name: "S2: the SQLite bucket stops going through the dialect and answers the raw date", file: "runtime/driver/dialects.mjs",
    find: "bucket: (col, unit) => `strftime('${UNITS[unit]}', ${col})`,",
    replace: "bucket: (col) => col," },
  { name: "S2: a boolean reads the column without COALESCE (SQL-only text: IFNULL is back)", file: "runtime/store/aggexpr.mjs",
    find: "boolInt(`COALESCE(${dia(cx).quote(f.name)},0) <> 0`)",
    replace: "boolInt(`IFNULL(${dia(cx).quote(f.name)},0) <> 0`)" },
  { name: "S2: a NULL boolean is not false any more (COALESCE default flipped)", file: "runtime/store/aggexpr.mjs",
    find: "boolInt(`COALESCE(${dia(cx).quote(f.name)},0) <> 0`)",
    replace: "boolInt(`COALESCE(${dia(cx).quote(f.name)},1) <> 0`)" },
  { name: "S2: an identifier is quoted without doubling an embedded quote", file: "runtime/driver/dialects.mjs",
    find: "const quote = (id) => `\"${String(id).replaceAll('\"', '\"\"')}\"`;",
    replace: "const quote = (id) => `\"${String(id)}\"`;" },
  { name: "S2: the outbox DDL leaves its column names unquoted (pg folds updatedAt to lower case)", file: "runtime/driver/dialects.mjs",
    find: "cols.map(([n, t]) => `${quote(n)} ${p.colType(t)}`)",
    replace: "cols.map(([n, t]) => `${n} ${p.colType(t)}`)" },
  { name: "S2: the session read leaves the reserved word user unquoted", file: "runtime/store/state.mjs",
    find: "SELECT ${q('user')} FROM",
    replace: "SELECT user FROM" },
  { name: "S2: the outbox update leaves a mixed-case column unquoted", file: "runtime/store/state.mjs",
    find: "sets.push(`${q(k)}=${ph(vals.length)}`)",
    replace: "sets.push(`${k}=${ph(vals.length)}`)" },
  { name: "S2: a session that signs in again is ignored instead of replacing the old row (SQLite upsert)", file: "runtime/driver/dialects.mjs",
    find: "`INSERT OR REPLACE INTO",
    replace: "`INSERT OR IGNORE INTO" },
  { name: "S2: the PostgreSQL upsert also rewrites its own key", file: "runtime/driver/dialects.mjs",
    find: "cols.filter((c) => c !== key).map(",
    replace: "cols.map(" },
  { name: "S2: the PostgreSQL upsert forgets to update on conflict", file: "runtime/driver/dialects.mjs",
    find: "DO UPDATE SET ${",
    replace: "DO NOTHING ${" },
  { name: "S2: a long PostgreSQL index name is cut without leaving room for the hash (over 63 bytes)", file: "runtime/driver/dialects.mjs",
    find: "> PG_NAME_MAX - 9) break;",
    replace: "> PG_NAME_MAX) break;" },
  { name: "S2: a truncated PostgreSQL index name loses its hash, so two long names with one head collide", file: "runtime/driver/dialects.mjs",
    find: "return `${head}_${fnv(full)}`;",
    replace: "return head;" },
  { name: "S2: a long index name is never shortened (the engine cuts it, the store never finds it again)", file: "runtime/driver/dialects.mjs",
    find: "if (bytes(full) <= PG_NAME_MAX) return full;",
    replace: "if (true) return full;" },
  { name: "S2: SQLite index names go through the PostgreSQL truncation (an existing index is dropped and recreated)", file: "runtime/driver/dialects.mjs",
    find: "indexName: (table, cols) => `idx_${table}_${cols.join('_')}`,",
    replace: "indexName: (table, cols) => pgIndexName(table, cols)," },
  { name: "S2: PostgreSQL sorts NULLs the other way round", file: "runtime/driver/dialects.mjs",
    find: "dir === 'ASC' ? 'FIRST' : 'LAST'",
    replace: "dir === 'ASC' ? 'LAST' : 'FIRST'" },
  { name: "S2: PostgreSQL ties have no id tie-break", file: "runtime/driver/dialects.mjs",
    find: "${tie ? ', id ASC' : ''}",
    replace: "${''}" },
  { name: "S2: PostgreSQL text sorts in the locale's order, not byte order", file: "runtime/driver/dialects.mjs",
    find: "${text ? ' COLLATE \"C\"' : ''}",
    replace: "${''}" },
  { name: "S2: a grouped text column sorts in the locale's order on PostgreSQL", file: "runtime/driver/dialects.mjs",
    find: "collate: (expr) => `${expr} COLLATE \"C\"`,",
    replace: "collate: (expr) => expr," },
  { name: "S2: PostgreSQL placeholders restart at $1 after earlier parameters", file: "runtime/driver/dialects.mjs",
    find: "p.ph(from + i)",
    replace: "p.ph(1 + i)" },
  { name: "S2: PostgreSQL named parameters are numbered from $0", file: "runtime/driver/dialects.mjs",
    find: "named: (_n, i) => `$${i + 1}`,",
    replace: "named: (_n, i) => `$${i}`," },
  { name: "S2: PostgreSQL binds today/now after the row values instead of before", file: "runtime/driver/dialects.mjs",
    find: "[...names.map((n) => named[n]), ...vals]",
    replace: "[...vals, ...names.map((n) => named[n])]" },
  { name: "S2: PostgreSQL stores int/bool/money in int4", file: "runtime/driver/dialects.mjs",
    find: "t.replace(/\\bINTEGER\\b/g, 'BIGINT')",
    replace: "t.replace(/\\bINTEGER\\b/g, 'INTEGER')" },
  { name: "S2: a boolean condition leaks NULL instead of 0", file: "runtime/driver/dialects.mjs",
    find: "d.boolInt = (cond) => `(CASE WHEN ${cond} THEN 1 ELSE 0 END)`;",
    replace: "d.boolInt = (cond) => `(CASE WHEN ${cond} THEN 1 END)`;" },
  { name: "S2: PostgreSQL insert forgets RETURNING id", file: "runtime/driver/dialects.mjs",
    find: "returning: ' RETURNING id',",
    replace: "returning: ''," },

  // C1: connector descriptors, the engine, connector.call
  { name: "C1: an unknown schema keyword is accepted", file: "runtime/connectors/schema.mjs",
    find: "    if (!KEYWORDS.includes(key)) {",
    replace: "    if (false) {" },
  { name: "C1: a required property may be missing", file: "runtime/connectors/schema.mjs",
    find: "if (value[k] === undefined) out.push(",
    replace: "if (false) out.push(" },
  { name: "C1: additionalProperties defaults to open instead of closed", file: "runtime/connectors/schema.mjs",
    find: "const extra = schema.additionalProperties ?? opts.extra;",
    replace: "const extra = schema.additionalProperties ?? !opts.extra;" },
  { name: "C1: an enum accepts any value", file: "runtime/connectors/schema.mjs",
    find: "if (schema.enum !== undefined && !schema.enum.some(",
    replace: "if (false && !schema.enum.some(" },
  { name: "C1: a string format is not checked", file: "runtime/connectors/schema.mjs",
    find: "if (schema.format !== undefined && !FORMATS",
    replace: "if (false && !FORMATS" },
  { name: "C1: a pattern is not checked", file: "runtime/connectors/schema.mjs",
    find: "if (schema.pattern !== undefined && !new RegExp",
    replace: "if (false && !new RegExp" },
  { name: "C1: a maximum is exclusive", file: "runtime/connectors/schema.mjs",
    find: "value > schema.maximum",
    replace: "value >= schema.maximum" },
  { name: "C1: a minimum is exclusive", file: "runtime/connectors/schema.mjs",
    find: "value < schema.minimum",
    replace: "value <= schema.minimum" },
  { name: "C1: a template scope nobody defined is accepted", file: "runtime/connectors/template.mjs",
    find: "if (!SCOPES.includes(scope)) throw",
    replace: "if (false) throw" },
  { name: "C1: a secret nobody resolves expands to nothing instead of failing", file: "runtime/connectors/template.mjs",
    find: "(scopes.secret || secretGone)(path[0])",
    replace: "(scopes.secret || (() => ''))(path[0])" },
  { name: "C1: an absent value leaves an undefined property in the body", file: "runtime/connectors/template.mjs",
    find: "} else if (x !== undefined) out[k] = x;",
    replace: "} else out[k] = x;" },
  { name: "C1: {secret.*} is allowed in a request url", file: "runtime/connectors/descriptor.mjs",
    find: "else if (scope === 'secret' && ctx.noSecret)",
    replace: "else if (scope === 'secret' && false)" },
  { name: "C1: {secret.*} is allowed in an app's connector url", file: "runtime/check/connectors.mjs",
    find: "if (/\\{secret\\./.test(url)) err(",
    replace: "if (false) err(" },
  { name: "C1: a credential in a connector url is allowed", file: "runtime/check/connectors.mjs",
    find: "else if (/\\/\\/[^/@]+:[^/@]*@/.test(url) || SECRET_IN_QUERY.test(url)) err(",
    replace: "else if (false) err(" },
  { name: "C1: a literal secret under a secret-looking key is allowed", file: "runtime/check/connectors.mjs",
    find: "(SECRETY_KEY.test(key) && value !== '') ||",
    replace: "(false && value !== '') ||" },
  { name: "C1: a secret-shaped value under an innocent key is allowed", file: "runtime/check/connectors.mjs",
    find: "|| SECRETY_VALUE.test(value)) err(",
    replace: "|| false) err(" },
  { name: "C1: an operation need not say whether it is idempotent", file: "runtime/connectors/descriptor.mjs",
    find: "if (typeof op.idempotent !== 'boolean')",
    replace: "if (false)" },
  { name: "C1: the idempotency key is usable before retries exist", file: "runtime/connectors/descriptor.mjs",
    find: "if (scope === 'key') out.push(",
    replace: "if (false) out.push(" },
  { name: "C1: timeoutMs may exceed half the lease", file: "runtime/connectors/descriptor.mjs",
    find: "d.timeoutMs <= MAX_TIMEOUT_MS",
    replace: "d.timeoutMs <= MAX_TIMEOUT_MS * 100" },
  { name: "C1: a descriptor plugin is registered without being checked", file: "runtime/registry.mjs",
    find: "if (bad.length) throw new Error(`${name}: invalid descriptor",
    replace: "if (false) throw new Error(`${name}: invalid descriptor" },
  { name: "C1: a descriptor may take the name of a registered kind", file: "runtime/registry.mjs",
    find: "if (registry.transports[kind]) throw new Error(`${name}: connector kind",
    replace: "if (false) throw new Error(`${name}: connector kind" },
  { name: "C1: the input is not validated at enqueue time", file: "runtime/connectors/engine.mjs",
    find: "if (bad.length) throw new Error(`${d.name}.${opName}",
    replace: "if (false) throw new Error(`${d.name}.${opName}" },
  { name: "C1: the stored input is not completed with its defaults", file: "runtime/connectors/engine.mjs",
    find: "const whole = withDefaults(op.input, input);",
    replace: "const whole = input;" },
  { name: "C1: a legacy row is sent to the url of the template, not its own target", file: "runtime/connectors/engine.mjs",
    find: "target: legacy ? row.target : undefined",
    replace: "target: undefined" },
  { name: "C1: the connector's timeout no longer wins over the descriptor's", file: "runtime/connectors/engine.mjs",
    find: "timeout: scopes.config.timeout || d.timeoutMs || DEFAULT_TIMEOUT_MS",
    replace: "timeout: d.timeoutMs || scopes.config.timeout || DEFAULT_TIMEOUT_MS" },
  { name: "C1: output validation is skipped", file: "runtime/connectors/engine.mjs",
    find: "const drift = validate(op.output, body, '', { extra: true });",
    replace: "const drift = [];" },
  { name: "C1: a drifting answer fails the delivery instead of only flagging it", file: "runtime/connectors/engine.mjs",
    find: "drift: drift.length ? 1 : 0 }, drift };",
    replace: "drift: drift.length ? 1 : 0, status: drift.length ? 'failed' : 'sent' }, drift };" },
  { name: "C1: a failed answer is read and validated as if it were the output", file: "runtime/connectors/engine.mjs",
    find: "if (!res.ok || !op.output) return",
    replace: "if (!op.output) return" },
  { name: "C1: contract drift is not traced", file: "runtime/connectors/engine.mjs",
    find: "if (drift.length) trace({",
    replace: "if (false) trace({" },
  { name: "C1: the connector's config is not validated by its descriptor", file: "runtime/connectors/engine.mjs",
    find: "validate: (connector) => validate(d.config || { type: 'object', properties: {} }, configOf(d, connector), '')",
    replace: "validate: (connector) => validate({ type: 'object', additionalProperties: true }, configOf(d, connector), '')" },
  { name: "C1: connector.call queues its row without the operation", file: "runtime/blocks.mjs",
    find: "payload: input, op: step.op })",
    replace: "payload: input, op: null })" },
  { name: "C1: connector.call queues the unvalidated input", file: "runtime/blocks.mjs",
    find: "payload: input, op: step.op })",
    replace: "payload: resolve(step.input), op: step.op })" },
  { name: "C1: connector.call skips the descriptor's own validation", file: "runtime/blocks.mjs",
    find: "const { input, target } = prepare(d, c, step.op, resolve(step.input));",
    replace: "const input = resolve(step.input); const target = c.url || '';" },
  { name: "C1: a literal input value is not validated by the checker", file: "runtime/check/calls.mjs",
    find: "else if (!isDynamic(v)) for (const [at, message] of validate(",
    replace: "else if (false) for (const [at, message] of validate(" },
  { name: "C1: a missing required input is not reported by the checker", file: "runtime/check/calls.mjs",
    find: "if (input[k] === undefined) h.err(",
    replace: "if (false) h.err(" },
  { name: "C1: an unknown input name is accepted by the checker", file: "runtime/check/calls.mjs",
    find: "if (!schema.additionalProperties) h.err(p, `unknown input",
    replace: "if (false) h.err(p, `unknown input" },
  { name: "C1: a @row.field of the wrong type is accepted by the checker", file: "runtime/check/calls.mjs",
    find: "if (have && schema.type && !compatible(schema.type, have))",
    replace: "if (false)" },
  { name: "C1: an int cannot fill a number input in the checker", file: "runtime/check/calls.mjs",
    find: "want === have || (want === 'number' && have === 'integer')",
    replace: "want === have" },
  { name: "C1: a dynamic value is validated as a literal by the checker", file: "runtime/check/calls.mjs",
    find: "(typeof v === 'string' ? v.startsWith('@') || isExpression(v)",
    replace: "(typeof v === 'string' ? false" },
  { name: "C1: a connector without a descriptor is accepted by connector.call's checker", file: "runtime/check/calls.mjs",
    find: "if (!d) return err(`${path}/connector`",
    replace: "if (false) return err(`${path}/connector`" },
  { name: "C1: an unknown operation is not reported by the checker", file: "runtime/check/calls.mjs",
    find: "  if (!op) {\n    const n = near",
    replace: "  if (false) {\n    const n = near" },
  { name: "C1: connector.call's own check never runs", file: "runtime/blocks.mjs",
    find: "    check: checkCall,\n",
    replace: "    check: () => {},\n" },
  { name: "C1: input values are not reference-checked in steps", file: "runtime/check/steps.mjs",
    find: "'to', 'path', 'input']",
    replace: "'to', 'path']" },
  { name: "C1: the outbox row gets no operation", file: "runtime/store/state.mjs",
    find: "[kind, connector, target, JSON.stringify(payload ?? null), op, 'queued', 0, at, at]",
    replace: "[kind, connector, target, JSON.stringify(payload ?? null), null, 'queued', 0, at, at]" },
  { name: "C1: the http built-in descriptor loses its default method", file: "runtime/connectors/builtin.mjs",
    find: "default: 'POST',",
    replace: "default: 'GET'," },
  { name: "C1: the http built-in descriptor stops merging the connector's headers", file: "runtime/connectors/builtin.mjs",
    find: "'...': { $: 'config.headers' }",
    replace: "'x-none': 'x'" },
  { name: "C1: the http built-in descriptor sends its body as the whole input", file: "runtime/connectors/builtin.mjs",
    find: "body: { $: 'input.body' }",
    replace: "body: { $: 'input' }" },
  { name: "C1: the delivery does not pass its trace to the transport", file: "runtime/outbox.mjs",
    find: "{ fetchImpl, trace }));",
    replace: "{ fetchImpl }));" },
];

const TEST_TIMEOUT = 60_000; // a mutation that hangs a test must still terminate, and quickly: this is not the coverage run

// A mutated runtime can hang a test instead of failing it; a hang is a detection too — but
// `node --test` forks one worker process per test file, and killing only the `node --test`
// parent leaves those workers running forever (they do not share its process group by
// default). `detached: true` makes the parent the leader of its own group, so on timeout
// `process.kill(-pid, …)` reaches the parent and every worker it forked, not just the one pid.
const run = () => new Promise((resolve) => {
  const files = fs.readdirSync('tests').filter((f) => f.endsWith('.test.mjs')).map((f) => `tests/${f}`);
  // A private TMPDIR per run, removed afterwards: a run killed on timeout cannot clean up after itself.
  const priv = fs.mkdtempSync(path.join(os.tmpdir(), 'ag-mutrun-'));
  const child = spawn('node', ['--no-warnings', '--test', ...files], { stdio: 'ignore', detached: true, env: { ...process.env, TMPDIR: priv } });
  let settled = false;
  const timer = setTimeout(() => { try { process.kill(-child.pid, 'SIGKILL'); } catch { /* already gone */ } }, TEST_TIMEOUT);
  const finish = (ok) => { if (settled) return; settled = true; clearTimeout(timer); fs.rmSync(priv, { recursive: true, force: true }); resolve(ok); };
  child.on('exit', (code) => finish(code === 0));
  child.on('error', () => finish(false));
});

if (!(await run())) { console.error('the suite is red before any mutation — fix that first'); process.exit(2); }

// An optional argument narrows the run to mutations whose name contains it.
const only = process.argv[2] || '';
let killed = 0;
const survivors = [];
const chosen = MUTATIONS.filter((m) => m.name.includes(only));
for (const m of chosen) {
  const original = fs.readFileSync(m.file, 'utf8');
  if (!original.includes(m.find)) {
    console.log(`? ${m.name}\n    the mutation no longer applies to ${m.file} — update it`);
    survivors.push(m.name);
    continue;
  }
  // An interrupted run must not leave the mutation in the source tree.
  const restore = () => { fs.writeFileSync(m.file, original); process.exit(130); };
  process.once('SIGINT', restore).once('SIGTERM', restore);
  fs.writeFileSync(m.file, original.replace(m.find, m.replace));
  const started = Date.now();
  const green = await run();
  const ms = Date.now() - started;
  fs.writeFileSync(m.file, original);
  process.off('SIGINT', restore).off('SIGTERM', restore);
  // Close to TEST_TIMEOUT means the mutation hung a test rather than failing it —
  // still a kill (the process group is gone either way), but worth flagging.
  const slow = ms > TEST_TIMEOUT * 0.8 ? ` (${(ms / 1000).toFixed(1)}s — hung, not failed)` : '';
  if (green) { survivors.push(m.name); console.log(`✗ SURVIVED  ${m.name}${slow}`); }
  else { killed++; console.log(`✓ killed    ${m.name}${slow}`); }
}

console.log(`\n${killed}/${chosen.length} мутаций убито`);
if (survivors.length) {
  console.log('\nвыжили (значит, эти утверждения ничем не проверены):');
  for (const s of survivors) console.log(`  • ${s}`);
}
process.exit(survivors.length ? 1 : 0);
