CREATE TABLE "customer" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" TEXT, "email" TEXT)
CREATE TABLE "order" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "title" TEXT, "status" TEXT, "total" BIGINT, "qty" BIGINT, "placed" TEXT, "seen" TEXT, "customer" TEXT, "done" BIGINT)
CREATE INDEX IF NOT EXISTS "idx_order_customer" ON "order" ("customer")
CREATE INDEX IF NOT EXISTS "idx_order_title_status" ON "order" ("title", "status")
CREATE INDEX IF NOT EXISTS "idx_order_status" ON "order" ("status")
CREATE TABLE "item" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "order" TEXT, "qty" BIGINT, "price" BIGINT, "ok" BIGINT, "due" TEXT, "disc" BIGINT)
CREATE INDEX IF NOT EXISTS "idx_item_order" ON "item" ("order")
CREATE TABLE "blank" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)
CREATE TABLE IF NOT EXISTS "_outbox" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "kind" TEXT, "connector" TEXT, "target" TEXT, "payload" TEXT, "status" TEXT, "code" BIGINT, "error" TEXT, "attempts" BIGINT DEFAULT 0, "at" TEXT, "updatedAt" TEXT, "claimedAt" BIGINT)
CREATE TABLE IF NOT EXISTS "_session" ("id" TEXT PRIMARY KEY, "user" BIGINT, "at" TEXT)
-- write
SELECT id FROM "order" WHERE "title"=$1 AND "status"=$2 AND id!=$3
INSERT INTO "order" ("title","status","total","qty","placed","seen","customer","done") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id
INSERT INTO "blank" DEFAULT VALUES RETURNING id
SELECT * FROM "order" WHERE id=$1
UPDATE "order" SET "title"=$1,"total"=$2 WHERE id=$3
DELETE FROM "order" WHERE id=$1
SELECT * FROM "order" WHERE id=$1
SELECT id FROM "customer" WHERE LOWER("name")=LOWER($1) AND id!=$2
SELECT id FROM "order" WHERE "qty"=$1 AND id!=$2
SELECT id FROM "order" WHERE "title"=$1 AND "status"=$2 AND id!=$3
SELECT COUNT(*) AS n FROM "order" WHERE "qty" >= $1
-- read
SELECT * FROM "order" WHERE "status"=$1 AND "qty" >= $2 AND "qty" <= $3 AND "qty" > $4 AND "qty" < $5 AND "qty" != $6 AND "qty" IN ($7,$8) AND "customer" IS NULL AND "seen" IS NOT NULL AND LOWER("title") LIKE $9 ESCAPE '\' AND (LOWER("title") LIKE $10 ESCAPE '\' OR LOWER("status") LIKE $11 ESCAPE '\') ORDER BY "title" COLLATE "C" ASC NULLS FIRST, id ASC
SELECT * FROM "order" ORDER BY "total" DESC NULLS LAST, id ASC
SELECT * FROM "order" ORDER BY id DESC
SELECT * FROM "order" WHERE "qty"=$1 ORDER BY "placed" COLLATE "C" DESC NULLS LAST, id ASC LIMIT $2 OFFSET $3
SELECT COUNT(*) AS n FROM "order" WHERE "done"=$1
SELECT * FROM "item" WHERE "order" IN ($1,$2,$3) ORDER BY id DESC
-- aggregate
SELECT SUBSTR("placed", 1, 7) COLLATE "C" AS grp, SUM("total") AS "sum_total", COUNT(*) AS "n" FROM "order" WHERE "status"=$1 GROUP BY grp ORDER BY "grp" ASC NULLS FIRST LIMIT 5
SELECT "status" COLLATE "C" AS grp, AVG("qty") AS "a" FROM "order" GROUP BY grp ORDER BY "a" DESC NULLS LAST
SELECT "qty" AS grp, MAX("qty") AS "m" FROM "order" GROUP BY grp ORDER BY "grp" DESC NULLS LAST
SELECT SUBSTR("seen", 1, 4) COLLATE "C" AS grp, MIN("total") AS "m" FROM "order" GROUP BY grp ORDER BY "grp" ASC NULLS FIRST
SELECT SUBSTR("placed", 1, 10) COLLATE "C" AS grp, COUNT(*) AS "n" FROM "order" GROUP BY grp
-- compiled aggregates
SELECT SUM(((CASE WHEN (CASE WHEN (CASE WHEN (CASE WHEN COALESCE("ok",0) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN (CASE WHEN "qty" > 1 THEN 1 ELSE 0 END) = 0 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 OR (CASE WHEN "price" IS NULL AND "disc" IS NULL THEN 0 WHEN "price" IS NULL OR "disc" IS NULL THEN 1 WHEN "price" != "disc" THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 THEN ("qty" * "price") ELSE (0 * 100) END) + ("qty" * 100))) AS v FROM "item" AS t0 WHERE t0."order"=$1
SELECT t0."order" AS grp, SUM(((CASE WHEN (CASE WHEN (CASE WHEN (CASE WHEN COALESCE("ok",0) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN (CASE WHEN "qty" > 1 THEN 1 ELSE 0 END) = 0 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 OR (CASE WHEN "price" IS NULL AND "disc" IS NULL THEN 0 WHEN "price" IS NULL OR "disc" IS NULL THEN 1 WHEN "price" != "disc" THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 THEN ("qty" * "price") ELSE (0 * 100) END) + ("qty" * 100))) AS v FROM "item" AS t0 WHERE t0."order" IN ($1,$2) GROUP BY t0."order"
SELECT COUNT(*) AS v FROM "item" AS t0 WHERE t0."order"=$3 AND ((CASE WHEN (CASE WHEN (CASE WHEN (CASE WHEN (CASE WHEN "due" >= $1 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN COALESCE("ok",0) <> 0 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN "due" < $2 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN "price" IS NULL AND (2 * 100) IS NULL THEN 1 WHEN "price" IS NULL OR (2 * 100) IS NULL THEN 0 WHEN "price" = (2 * 100) THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN "qty" IS NULL AND 1 IS NULL THEN 0 WHEN "qty" IS NULL OR 1 IS NULL THEN 1 WHEN "qty" != 1 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0)
SELECT t0."order" AS grp, COUNT(*) AS v FROM "item" AS t0 WHERE t0."order" IN ($3) AND ((CASE WHEN (CASE WHEN (CASE WHEN (CASE WHEN (CASE WHEN "due" >= $1 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN COALESCE("ok",0) <> 0 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN "due" < $2 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN "price" IS NULL AND (2 * 100) IS NULL THEN 1 WHEN "price" IS NULL OR (2 * 100) IS NULL THEN 0 WHEN "price" = (2 * 100) THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0 AND (CASE WHEN "qty" IS NULL AND 1 IS NULL THEN 0 WHEN "qty" IS NULL OR 1 IS NULL THEN 1 WHEN "qty" != 1 THEN 1 ELSE 0 END) <> 0 THEN 1 ELSE 0 END) <> 0) GROUP BY t0."order"
SELECT SUM(("total" + ((SELECT COUNT(*) FROM "item" AS t1 WHERE t1."order" = CAST(t0."id" AS TEXT) AND ((CASE WHEN COALESCE("ok",0) <> 0 THEN 1 ELSE 0 END) <> 0)) * 100))) AS v FROM "order" AS t0 WHERE t0."customer"=$1
-- outbox and sessions
INSERT INTO "_outbox" ("kind","connector","target","payload","status","attempts","at","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id
SELECT * FROM "_outbox" WHERE "status"=$1 AND "id"=$2 ORDER BY id DESC
SELECT * FROM "_outbox" WHERE "status"='queued' OR ("status"='sending' AND "claimedAt"<=$1) ORDER BY id ASC
UPDATE "_outbox" SET "status"='sending', "claimedAt"=$1, "updatedAt"=$2 WHERE id=$3 AND ("status"='queued' OR ("status"='sending' AND "claimedAt"<=$4))
UPDATE "_outbox" SET "status"=$1,"error"=$2,"updatedAt"=$3 WHERE id=$4
UPDATE "_outbox" SET "status"=$1,"code"=$2,"updatedAt"=$3 WHERE id=$4 AND "claimedAt"=$5 AND "status"='sending'
INSERT INTO "_session" ("id", "user", "at") VALUES ($1,$2,$3) ON CONFLICT ("id") DO UPDATE SET "user"=EXCLUDED."user", "at"=EXCLUDED."at"
SELECT "user" FROM "_session" WHERE id=$1
DELETE FROM "_session" WHERE id=$1
